# 工作流名称
name: Build Docker Image

on:
  workflow_dispatch:
  
# 定义环境变量, 后面会使用
# 定义 APP_NAME 用于 docker build-args
# 定义 DOCKERHUB_REPO 标记 docker hub repo 名称
env:
  APP_NAME: httpproxy
  DOCKERHUB_REPO: isayme/httpproxy
  
  
